require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1' # Ensure this matches or exceeds the minimum required deployment target

prepare_react_native_project!

target 'LovenigatorApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'LovenigatorAppTests' do
    inherit! :complete
    inhibit_all_warnings! # Suppresses warnings from Pods
  end

  # Post-installation configurations
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Ensure deployment target is set to 16.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'

        # Exclude arm64 for iPhone simulator to avoid build issues on Apple Silicon
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end

    # Fix for React Native Fabric integration
    react_native_post_install(installer)
  end
end
